name: Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        working-directory: ./Garciss.ROP
        run: dotnet restore

      - name: Build
        working-directory: ./Garciss.ROP
        run: dotnet build --no-restore

      - name: Test
        working-directory: ./Garciss.ROP
        run: dotnet test --no-build --verbosity normal

      - name: Set project paths
        run: echo "PROJECT_PATHS=Garciss.ROP/Garciss.ROP/Garciss.ROP.csproj Garciss.ROP/Garciss.ROP.ApiExtensions/Garciss.ROP.ApiExtensions.csproj" >> $GITHUB_ENV

      - name: Pack all projects
        run: |
          for proj in $PROJECT_PATHS
          do
            dotnet pack "$proj" --configuration Release --output ./packages
          done

      - name: Publish to NuGet
        run: dotnet nuget push "./packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate